name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Subir servidor do Serverest
      run: nohup npm run start &

    - name: Instalar dependências do node
      run: npm install -f

    - name: Executar os testes
      run: npm run cypress:report

    - name: Verificar resultados dos testes
      run: ls -la allure-results  # Certifique-se de que os arquivos de resultados estão presentes

    - name: Gerar relatório Allure
      run: npm run allure:generate  # Gera o relatório Allure

    - name: Verificar relatório Allure
      run: ls -la allure-report  # Verifique se os arquivos HTML estão presentes

    - name: Criar arquivo .nojekyll
      run: echo "" > allure-report/.nojekyll

    - name: Publicar relatório Allure no GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./allure-report  # Diretório correto
        publish_branch: gh-pages
